name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: PR coverage
        run: |
          cargo llvm-cov test --json --output-path pr_coverage.json
          lines=$(jq '.data[].totals.lines.percent' pr_coverage.json)
          functions=$(jq '.data[].totals.functions.percent' pr_coverage.json)
          echo "pr_lines=$lines" >> $GITHUB_ENV
          echo "pr_functions=$functions" >> $GITHUB_ENV
          echo "PR coverage - lines: $lines, functions: $functions"
      - name: Checkout main
        run: git checkout origin/main
      - name: Main coverage
        run: |
          cargo llvm-cov test --json --output-path main_coverage.json
          lines=$(jq '.data[].totals.lines.percent' main_coverage.json)
          functions=$(jq '.data[].totals.functions.percent' main_coverage.json)
          echo "main_lines=$lines" >> $GITHUB_ENV
          echo "main_functions=$functions" >> $GITHUB_ENV
          echo "Main coverage - lines: $lines, functions: $functions"

